# Generated by Django 3.2.2 on 2021-07-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_database_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='country',
        ),
    ]
